package vn.toancauxanh.gg.model.enums;

public enum QuocGiaEnum {
	AFGHANISTAN("Afghanistan"),
	AI_CAP("Ai Cập"),
	ALBANIA("Albania"),
	ALGIERI("Algérie"),
	ANDORRA("Andorra"),
	ANGOLA("Angola"),
	VUONG_QUOC_ANH("Vương quốc Liên hiệp Anh và Bắc Ireland"),
	ANTIGUA("Antigua và Barbuda"),
	AO("Áo"),
	A_RAP("Ả Rập Xê Út"),
	ARMENIA("Armenia"),
	ARGHENTINA("Argentina"),
	AZERBAIJAN("Azerbaijan"),
	AN_DO("Ấn Độ"),
	BAHAMAS("Bahamas"),
	BAHRAIN("Bahrain"),
	BA_LAN("Ba Lan"),
	BANGLADESH("Bangladesh"),
	BARBADOS("Barbados"),
	BELARUS("Belarus"),
	BELIZE("Belize"),
	BENIN("Bénin"),
	BHUTAN("Bhutan"),
	BI("Bỉ"),
	BOLIVIA("Bolivia"),
	BOSNA_AND_HERCEGOVIA("Bosna và Hercegovina"),
	BOTSWANA("Botswana"),
	BO_DAO_NHA("Bồ Đào Nha"),
	BO_BIEN_NGA("Bờ Biển Ngà"),
	BRASIL("Brasil"),
	BRUNEI("Brunei"),
	BULGARIA("Bulgaria"),
	BURKIRA_FASO("Burkina Faso"),
	BURUNDI("Burundi"),
	CABO_VERDE("Cabo Verde"),
	UAE("UAE"),
	CAMEROON("Cameroon"),
	CAMPUCHIA("Campuchia"),
	CANADA("Canada"),
	CHILE("Chile"),
	COLOMBIA("Colombia"),
	COMOROS("Comoros"),
	CONGO("Cộng hòa Congo"),
	CONG_HOA_CONGO("Cộng hòa Dân chủ Congo"),
	COSTA_RICA("Costa Rica"),
	CROATIA("Croatia"),
	CUBA("Cuba"),
	DJIBOUTI("Djibouti"),
	DOMINICA("Dominica"),
	CONG_HOA_DOMINICA("Cộng hòa Dominica"),
	DAN_MACH("Đan Mạch"),
	DONG_TIMOR("Đông Timor"),
	DUC("Đức"),
	ECUADOR("Ecuador"),
	EL_SALVADOR("El Salvador"),
	ERITREA("Eritrea"),
	ESTONIA("Estonia"),
	FIJI("Fiji"),
	GABON("Gabon"),
	GAMBIA("Gambia"),
	GHANA("Ghana"),
	GRENADA("Grenada"),
	GRUZIA("Gruzia"),
	GUATEMALA("Guatemala"),
	GUINE_BISSAU("Guiné-Bissau"),
	GUINE_XICH_DAO("Guinea Xích Đạo"),
	GUINEE("Guinée"),
	GUYANA("Guyana"),
	HAITI("Haiti"),
	HA_LAN("Hà Lan"),
	HAN_QUOC("Hàn Quốc"),
	HOA_KY("Hoa Kỳ"),
	HONDURAS("Honduras"),
	HUNGARY("Hungary"),
	HY_LAP("Hy Lạp"),
	ICELAND("Iceland"),
	INDONESIA("Indonesia"),
	IRAN("Iran"),
	IRAQ("Iraq"),
	IRELAND("Ireland"),
	ISRAEL("Israel"),
	JAMAICA("Jamaica"),
	JORDAN("Jordan"),
	KAZAKHSTAN("Kazakhstan"),
	KENYA("Kenya"),
	KIRIBATI("Kiribati"),
	KOSOVO("Kosovo"),
	KUWAIT("Kuwait"),
	KYRGYZSTAN("Kyrgyzstan"),
	LAO("Lào"),
	LATVIA("Latvia"),
	LESOTHO("Lesotho"),
	LIBAN("Liban"),
	LIBERIA("Liberia"),
	LIBYA("Libya"),
	LIECHTENSTEIN("Liechtenstein"),
	LITVA("Litva"),
	LUXEMBOURG("Luxembourg"),
	MACEDONIA("Macedonia"),
	MADAGASCAR("Madagascar"),
	MALAWI("Malawi"),
	MALAYSIA("Malaysia"),
	MALDIVES("Maldives"),
	MALI("Mali"),
	MALTA("Malta"),
	MAROC("Maroc"),
	MARSHALL("Quần đảo Marshall"),
	MAURITANIE("Mauritanie"),
	MAURITIUS("Mauritius"),
	MEXICO("México"),
	MICRONESIA("Micronesia"),
	MOLDOVA("Moldova"),
	MONACO("Monaco"),
	MONG_CO("Mông Cổ"),
	MONTENEGRO("Montenegro"),
	MOZAMBIQUE("Mozambique"),
	MYANMAR("Myanmar"),
	NAMIBIA("Namibia"),
	NAM_SUDAN("Nam Sudan"),
	NAM_PHI("Nam Phi"),
	NAURU("Nauru"),
	NA_UY("Na Uy"),
	NEPAL("Nepal"),
	NEW_ZEALAND("New Zealand"),
	NICARAGUA("Nicaragua"),
	NIGER("Niger"),
	NIGERIA("Nigeria"),
	NGA("Nga"),
	NHAT_BAN("Nhật Bản"),
	OMAN("Oman"),
	PAKISTAN("Pakistan"),
	PALAU("Palau"),
	PALESTINE("Palestine"),
	PANAMA("Panama"),
	PAPUA_NEW_GUINEA("Papua New Guinea"),
	PARAGUAY("Paraguay"),
	PERU("Peru"),
	PHAP("Pháp"),
	PHAN_LAN("Phần Lan"),
	PHILIPPINES("Philippines"),
	QUATAR("Qatar"),
	ROMANIA("România"),
	RWANDA("Rwanda"),
	SAINT_KITTS_NEVIS("Saint Kitts và Nevis"),
	SAINT_LUCIA("Saint Lucia"),
	SAINT_VINCENT_GRENADINES("Saint Vincent và Grenadines"),
	SAMOA("Samoa"),
	SAN_MARINO("San Marino"),
	SAO_TOME_PRINCIPE("São Tomé và Príncipe"),
	SEC("Séc"),
	SENEGAL("Sénégal"),
	SERBIA("Serbia"),
	SEYCHELLES("Seychelles"),
	SIERRA_LEONE("Sierra Leone"),
	SINGAPORE("Singapore"),
	SIP("Síp"),
	SLOVAKIA("Slovakia"),
	SLOVENIA("Slovenia"),
	SOLOMON("Solomon"),
	SOMALIA("Somalia"),
	SRI_LANKA("Sri Lanka"),
	SUDAN("Sudan"),
	SURINAME("Suriname"),
	SWAZILAND("Swaziland"),
	SYRIA("Syria"),
	TAJIKISTAN("Tajikistan"),
	TAY_BAN_NHA("Tây Ban Nha"),
	TCHAD("Tchad"),
	THAI_LAN("Thái Lan"),
	THO_NHI_KY("Thổ Nhĩ Kỳ"),
	THUY_DIEN("Thụy Điển"),
	THUY_SI("Thụy Sĩ"),
	TOGO("Togo"),
	TONGA("Tonga"),
	TRIEU_TIEN("Triều Tiên"),
	TRINIDAD_VA_TOBAGO("Trinidad và Tobago"),
	TRUNG_QUOC("Trung Quốc"),
	TRUNG_PHI("Trung Phi"),
	TUNISIA("Tunisia"),
	TURKMENISTAN("Turkmenistan"),
	TUVALU("Tuvalu"),
	UC("Úc"),
	UGANDA("Uganda"),
	UKRAINA("Ukraina"),
	URUGUAY("Uruguay"),
	UZBEKISTAN("Uzbekistan"),
	VANUATU("Vanuatu"),
	VATICAN("Vatican"),
	VENEZUELA("Venezuela"),
	VIET_NAM("Việt Nam"),
	Y("Ý"),
	YEMEN("Yemen"),
	ZAMBIA("Zambia"),
	ZIMBABWE("Zimbabwe");
	
	String text;

	QuocGiaEnum(final String txt) {
		text = txt;
	}

	public String getText() {
		return text;
	}
}
